import type { SectionCatalogEntry } from "@chaibuilder/sdk/types";

export const langlionSectionCatalogEntries: SectionCatalogEntry[] = [
  { type: "GroupTypeCard", labelKey: "Course card", category: "cards", role: "template", thumbnail: "auto", pickerCategory: "Produkty" },
  { type: "InstructorCard", labelKey: "Instructor", category: "cards", role: "template", thumbnail: "auto", pickerCategory: "Narracja" },
  { type: "BookingButton", labelKey: "Booking button", category: "forms", role: "template", thumbnail: "auto", pickerCategory: "Formularze" },
  { type: "UpcomingEvents", labelKey: "Upcoming events", category: "cards", role: "template", thumbnail: "auto", pickerCategory: "Produkty" },
  { type: "BlogPostTitle", labelKey: "Blog post title", category: "media", role: "template", thumbnail: "auto", pickerCategory: "Narracja" },
  { type: "BlogPostContent", labelKey: "Blog post content", category: "media", role: "template", thumbnail: "auto", pickerCategory: "Narracja" },
  { type: "BlogPostImage", labelKey: "Blog post image", category: "media", role: "template", thumbnail: "auto", pickerCategory: "Narracja" },
  { type: "BlogPostAuthor", labelKey: "Blog post author", category: "media", role: "template", thumbnail: "auto", pickerCategory: "Narracja" },
  { type: "BlogPostDate", labelKey: "Blog post date", category: "media", role: "template", thumbnail: "auto", pickerCategory: "Narracja" },
  { type: "BlogPostExcerpt", labelKey: "Blog post excerpt", category: "media", role: "template", thumbnail: "auto", pickerCategory: "Narracja" },
  { type: "BlogPostTags", labelKey: "Blog post tags", category: "media", role: "template", thumbnail: "auto", pickerCategory: "Narracja" },
  { type: "BlogPostList", labelKey: "Blog post list", category: "media", role: "template", thumbnail: "auto", pickerCategory: "Narracja" },
  { type: "BlogPagination", labelKey: "Blog pagination", category: "media", role: "template", thumbnail: "auto", pickerCategory: "Narracja" },
  { type: "EnrollmentHero", labelKey: "Enrollment hero", category: "hero", role: "template", thumbnail: "auto" },
  { type: "EnrollmentSchedule", labelKey: "Enrollment schedule", category: "cards", role: "template", thumbnail: "auto" },
  { type: "EnrollmentPricing", labelKey: "Enrollment pricing", category: "pricing", role: "template", thumbnail: "auto" },
  { type: "EnrollmentInstructors", labelKey: "Enrollment instructors", category: "cards", role: "template", thumbnail: "auto" },
  { type: "EnrollmentPolicy", labelKey: "Enrollment policy", category: "forms", role: "template", thumbnail: "auto" },
  { type: "EnrollmentBookingButton", labelKey: "Enrollment booking button", category: "forms", role: "template", thumbnail: "auto" },
  { type: "EnrollmentBookingFlow", labelKey: "Enrollment booking flow", category: "forms", role: "template", thumbnail: "auto" },
  { type: "EnrollmentList", labelKey: "Enrollment list", category: "cards", role: "template", thumbnail: "auto" },
];