-- Migration: 003-create-payload-system-tables
-- Creates missing Payload CMS internal system tables (preferences, migrations,
-- kv store, locked documents). These are NOT tenant-scoped — they are Payload's
-- own bookkeeping, not academy data — so no organization_id or RLS.
--
-- ⚠️ This DDL was GENERATED by `payload generate:db-schema` (2026-07-27) and
-- then transcribed to raw SQL. DO NOT hand-edit column names/types — if Payload
-- updates its internal schema, re-run the generator.
--
-- Run via: docker exec -i saas_school_postgres psql -U postgres -d saas_boilerplate \
--   < migrations/003-create-payload-system-tables.sql

BEGIN;

-- ============================================================
-- 1. payload_preferences + rels — user UI state
-- ============================================================
CREATE TABLE IF NOT EXISTS "payload_preferences" (
    "id" serial PRIMARY KEY,
    "key" varchar,
    "value" jsonb,
    "updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
    "created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS "payload_preferences_key_idx" ON "payload_preferences" ("key");
CREATE INDEX IF NOT EXISTS "payload_preferences_updated_at_idx" ON "payload_preferences" ("updated_at");
CREATE INDEX IF NOT EXISTS "payload_preferences_created_at_idx" ON "payload_preferences" ("created_at");

CREATE TABLE IF NOT EXISTS "payload_preferences_rels" (
    "id" serial PRIMARY KEY,
    "order" integer,
    "parent_id" integer NOT NULL,
    "path" varchar NOT NULL,
    "payload_admin_users_id" integer
);

CREATE INDEX IF NOT EXISTS "payload_preferences_rels_order_idx" ON "payload_preferences_rels" ("order");
CREATE INDEX IF NOT EXISTS "payload_preferences_rels_parent_idx" ON "payload_preferences_rels" ("parent_id");
CREATE INDEX IF NOT EXISTS "payload_preferences_rels_path_idx" ON "payload_preferences_rels" ("path");
CREATE INDEX IF NOT EXISTS "payload_preferences_rels_payload_admin_users_id_idx" ON "payload_preferences_rels" ("payload_admin_users_id");

ALTER TABLE "payload_preferences_rels" ADD CONSTRAINT "payload_preferences_rels_parent_fk"
  FOREIGN KEY ("parent_id") REFERENCES "payload_preferences"("id") ON DELETE CASCADE;
ALTER TABLE "payload_preferences_rels" ADD CONSTRAINT "payload_preferences_rels_users_fk"
  FOREIGN KEY ("payload_admin_users_id") REFERENCES "payload_admin_users"("id") ON DELETE CASCADE;

-- ============================================================
-- 2. payload_migrations — Payload's own migration tracking
-- ============================================================
CREATE TABLE IF NOT EXISTS "payload_migrations" (
    "id" serial PRIMARY KEY,
    "name" varchar,
    "batch" numeric,
    "updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
    "created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS "payload_migrations_updated_at_idx" ON "payload_migrations" ("updated_at");
CREATE INDEX IF NOT EXISTS "payload_migrations_created_at_idx" ON "payload_migrations" ("created_at");

-- ============================================================
-- 3. payload_kv — key-value store (used internally by Payload)
-- ============================================================
CREATE TABLE IF NOT EXISTS "payload_kv" (
    "id" serial PRIMARY KEY,
    "key" varchar NOT NULL,
    "data" jsonb NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "payload_kv_key_idx" ON "payload_kv" ("key");

-- ============================================================
-- 4. payload_locked_documents + rels — document locking
-- ============================================================
--
-- ⚠️ KNOWN RISK — no tenant isolation on locked documents.
-- payload_locked_documents_rels has FK columns to tenant-scoped tables
-- (pages, media, theme), but neither table carries organization_id.
-- Adding RLS with subqueries through _rels is possible but fragile:
-- it would need per-collection JOINs, breaks with every new lockable
-- collection, and does not cover payload_admin_users_id (non-tenant).
-- Risk accepted as low: lock data is ephemeral (lifetime of an edit
-- session), carries metadata only (who is editing what, not content),
-- and Payload's own auth strategy already rejects cross-tenant access
-- at the application layer. Revisit before production if the security
-- surface expands (e.g. sensitive document types added).

CREATE TABLE IF NOT EXISTS "payload_locked_documents" (
    "id" serial PRIMARY KEY,
    "global_slug" varchar,
    "updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
    "created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS "payload_locked_documents_global_slug_idx" ON "payload_locked_documents" ("global_slug");
CREATE INDEX IF NOT EXISTS "payload_locked_documents_updated_at_idx" ON "payload_locked_documents" ("updated_at");
CREATE INDEX IF NOT EXISTS "payload_locked_documents_created_at_idx" ON "payload_locked_documents" ("created_at");

CREATE TABLE IF NOT EXISTS "payload_locked_documents_rels" (
    "id" serial PRIMARY KEY,
    "order" integer,
    "parent_id" integer NOT NULL,
    "path" varchar NOT NULL,
    "pages_id" integer,
    "media_id" integer,
    "theme_id" integer,
    "payload_admin_users_id" integer
);

CREATE INDEX IF NOT EXISTS "payload_locked_documents_rels_order_idx" ON "payload_locked_documents_rels" ("order");
CREATE INDEX IF NOT EXISTS "payload_locked_documents_rels_parent_idx" ON "payload_locked_documents_rels" ("parent_id");
CREATE INDEX IF NOT EXISTS "payload_locked_documents_rels_path_idx" ON "payload_locked_documents_rels" ("path");
CREATE INDEX IF NOT EXISTS "payload_locked_documents_rels_pages_id_idx" ON "payload_locked_documents_rels" ("pages_id");
CREATE INDEX IF NOT EXISTS "payload_locked_documents_rels_media_id_idx" ON "payload_locked_documents_rels" ("media_id");
CREATE INDEX IF NOT EXISTS "payload_locked_documents_rels_theme_id_idx" ON "payload_locked_documents_rels" ("theme_id");
CREATE INDEX IF NOT EXISTS "payload_locked_documents_rels_payload_admin_users_id_idx" ON "payload_locked_documents_rels" ("payload_admin_users_id");

ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_parent_fk"
  FOREIGN KEY ("parent_id") REFERENCES "payload_locked_documents"("id") ON DELETE CASCADE;
ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_pages_fk"
  FOREIGN KEY ("pages_id") REFERENCES "pages"("id") ON DELETE CASCADE;
ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_media_fk"
  FOREIGN KEY ("media_id") REFERENCES "media"("id") ON DELETE CASCADE;
ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_theme_fk"
  FOREIGN KEY ("theme_id") REFERENCES "theme"("id") ON DELETE CASCADE;
ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_users_fk"
  FOREIGN KEY ("payload_admin_users_id") REFERENCES "payload_admin_users"("id") ON DELETE CASCADE;

COMMIT;

-- Verification (run separately after COMMIT):
-- SELECT tablename FROM pg_catalog.pg_tables
-- WHERE schemaname = 'public'
--   AND tablename IN (
--     'payload_preferences', 'payload_preferences_rels',
--     'payload_migrations',
--     'payload_kv',
--     'payload_locked_documents', 'payload_locked_documents_rels'
--   )
-- ORDER BY 1;
