/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  serial,
  varchar,
  jsonb,
  timestamp,
  integer,
  boolean,
  numeric,
  pgEnum,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
export const enum_pages_status = pgEnum("enum_pages_status", ["draft", "published"]);
export const enum__pages_v_version_status = pgEnum("enum__pages_v_version_status", [
  "draft",
  "published",
]);

export const pages = pgTable(
  "pages",
  {
    id: serial("id").primaryKey(),
    title: varchar("title"),
    slug: varchar("slug"),
    status: enum_pages_status("status").default("draft"),
    blocks: jsonb("blocks"),
    seoDescription: varchar("seo_description"),
    updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    _status: enum_pages_status("_status").default("draft"),
  },
  (columns) => [
    index("pages_slug_idx").on(columns.slug),
    index("pages_updated_at_idx").on(columns.updatedAt),
    index("pages_created_at_idx").on(columns.createdAt),
    index("pages__status_idx").on(columns._status),
  ],
);

export const _pages_v = pgTable(
  "_pages_v",
  {
    id: serial("id").primaryKey(),
    parent: integer("parent_id").references(() => pages.id, {
      onDelete: "set null",
    }),
    version_title: varchar("version_title"),
    version_slug: varchar("version_slug"),
    version_status: enum__pages_v_version_status("version_status").default("draft"),
    version_blocks: jsonb("version_blocks"),
    version_seoDescription: varchar("version_seo_description"),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status: enum__pages_v_version_status("version__status").default("draft"),
    createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    latest: boolean("latest"),
  },
  (columns) => [
    index("_pages_v_parent_idx").on(columns.parent),
    index("_pages_v_version_version_slug_idx").on(columns.version_slug),
    index("_pages_v_version_version_updated_at_idx").on(columns.version_updatedAt),
    index("_pages_v_version_version_created_at_idx").on(columns.version_createdAt),
    index("_pages_v_version_version__status_idx").on(columns.version__status),
    index("_pages_v_created_at_idx").on(columns.createdAt),
    index("_pages_v_updated_at_idx").on(columns.updatedAt),
    index("_pages_v_latest_idx").on(columns.latest),
  ],
);

export const media = pgTable(
  "media",
  {
    id: serial("id").primaryKey(),
    altText: varchar("alt_text"),
    fileId: varchar("file_id").notNull(),
    updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
  },
  (columns) => [
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
  ],
);

export const theme = pgTable(
  "theme",
  {
    id: serial("id").primaryKey(),
    fontPrimary: varchar("font_primary").notNull(),
    fontHeading: varchar("font_heading").notNull(),
    colorPrimary: varchar("color_primary").notNull(),
    colorSecondary: varchar("color_secondary").notNull(),
    updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("theme_updated_at_idx").on(columns.updatedAt),
    index("theme_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_admin_users = pgTable(
  "payload_admin_users",
  {
    id: serial("id").primaryKey(),
    email: varchar("email").notNull(),
    updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("payload_admin_users_email_idx").on(columns.email),
    index("payload_admin_users_updated_at_idx").on(columns.updatedAt),
    index("payload_admin_users_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_kv = pgTable(
  "payload_kv",
  {
    id: serial("id").primaryKey(),
    key: varchar("key").notNull(),
    data: jsonb("data").notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    pagesID: integer("pages_id"),
    mediaID: integer("media_id"),
    themeID: integer("theme_id"),
    usersID: integer("payload_admin_users_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_pages_id_idx").on(columns.pagesID),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    index("payload_locked_documents_rels_theme_id_idx").on(columns.themeID),
    index("payload_locked_documents_rels_payload_admin_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["pagesID"]],
      foreignColumns: [pages.id],
      name: "payload_locked_documents_rels_pages_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["themeID"]],
      foreignColumns: [theme.id],
      name: "payload_locked_documents_rels_theme_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [payload_admin_users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("payload_admin_users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_payload_admin_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [payload_admin_users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: timestamp("updated_at", { mode: "string", withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", { mode: "string", withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const relations_pages = relations(pages, () => ({}));
export const relations__pages_v = relations(_pages_v, ({ one }) => ({
  parent: one(pages, {
    fields: [_pages_v.parent],
    references: [pages.id],
    relationName: "parent",
  }),
}));
export const relations_media = relations(media, () => ({}));
export const relations_theme = relations(theme, () => ({}));
export const relations_payload_admin_users = relations(payload_admin_users, () => ({}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    pagesID: one(pages, {
      fields: [payload_locked_documents_rels.pagesID],
      references: [pages.id],
      relationName: "pages",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    themeID: one(theme, {
      fields: [payload_locked_documents_rels.themeID],
      references: [theme.id],
      relationName: "theme",
    }),
    usersID: one(payload_admin_users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [payload_admin_users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(payload_admin_users, {
      fields: [payload_preferences_rels.usersID],
      references: [payload_admin_users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: "_rels",
  }),
}));
export const relations_payload_migrations = relations(payload_migrations, () => ({}));

type DatabaseSchema = {
  enum_pages_status: typeof enum_pages_status;
  enum__pages_v_version_status: typeof enum__pages_v_version_status;
  pages: typeof pages;
  _pages_v: typeof _pages_v;
  media: typeof media;
  theme: typeof theme;
  payload_admin_users: typeof payload_admin_users;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  relations_pages: typeof relations_pages;
  relations__pages_v: typeof relations__pages_v;
  relations_media: typeof relations_media;
  relations_theme: typeof relations_theme;
  relations_payload_admin_users: typeof relations_payload_admin_users;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    // @ts-expect-error — Payload-generated schema; TypeScript sees duplicate DatabaseSchema (kosmetyka)
    schema: DatabaseSchema;
  }
}
